name: Publish JavaDocs
on:
  push:	
    branches:	
      - master
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11.0.x
    - name: Build with Maven
      run: mvn -B javadoc:javadoc --file pom.xml
    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: target/site/
